import Head from "next/head";

import Header from "./components/header/Header";

export default function Home() {
  return (
    <>
      <Head>
        <title>Ecommerce app</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main></main>
    </>
  );
}
